routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/somepage', function () {
    return view('somepage');
});
Route::get('/pwdresetform', function () {
    return view('pwdresetform');
});

Route::get('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::post('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::get('pwdchange', 'App\Http\Controllers\pwdresetController@pwdreset_steptwo');
Route::get('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');
Route::post('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('pwdresets', App\Http\Controllers\pwdresetController::class);

Route::resource('basicdatas', App\Http\Controllers\basicdatasController::class);

Route::resource('jobs', App\Http\Controllers\jobsController::class);

Route::resource('dtjobs', App\Http\Controllers\dtjobsController::class);

Route::resource('pulldown1s', App\Http\Controllers\pulldown1sController::class);

Route::resource('testfield1s', App\Http\Controllers\testfield1sController::class);

Route::resource('testfield2s', App\Http\Controllers\testfield2sController::class);

Route::resource('testfield3s', App\Http\Controllers\testfield3sController::class);

Route::resource('jobcategories', App\Http\Controllers\jobcategoriesController::class);

Route::resource('articles', App\Http\Controllers\ArticlesController::class);

Route::resource('articlecategories', App\Http\Controllers\ArticlecategoriesController::class);

Route::resource('lessons', App\Http\Controllers\lessonsController::class);

Route::resource('catDefAgeGroups', App\Http\Controllers\CatDef_AgeGroupController::class);

Route::resource('catDefSubjects', App\Http\Controllers\CatDef_SubjectController::class);

Route::resource('catDefTopics', App\Http\Controllers\CatDef_TopicController::class);

Route::resource('catDefConcepts', App\Http\Controllers\CatDef_ConceptController::class);

Route::resource('lessonsTwoCols', App\Http\Controllers\LessonsTwoColsController::class);

Route::resource('lessonsadvs', App\Http\Controllers\LessonsadvController::class);

Route::resource('applicationTrackings', App\Http\Controllers\Application_TrackingController::class);

Route::resource('postAdverts', App\Http\Controllers\Post_AdvertsController::class);

Route::resource('employers', App\Http\Controllers\employerController::class);

Route::resource('employerjobs', App\Http\Controllers\EmployerjobsController::class);

Route::resource('employerJobApplications', App\Http\Controllers\EmployerJobApplicationController::class);

app/Models/CatDef_Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;



/**
 * Class CatDef_Topic
 * @package App\Models
 * @version April 13, 2021, 6:05 pm UTC
 *
 * @property string $brid
 * @property string $optionval
 * @property string $parent
 */
class CatDef_Topic extends Model
{


    public $table = 'cat_def__topics';
    



    public $fillable = [
        'brid',
        'optionval',
        'parent'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'brid' => 'string',
        'optionval' => 'string',
        'parent' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/CatDef_TopicController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCatDef_TopicRequest;
use App\Http\Requests\UpdateCatDef_TopicRequest;
use App\Repositories\CatDef_TopicRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CatDef_TopicController extends AppBaseController
{
    /** @var  CatDef_TopicRepository */
    private $catDefTopicRepository;

    public function __construct(CatDef_TopicRepository $catDefTopicRepo)
    {
        $this->catDefTopicRepository = $catDefTopicRepo;
    }

    /**
     * Display a listing of the CatDef_Topic.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $catDefTopics = $this->catDefTopicRepository->all();

        return view('cat_def__topics.index')
            ->with('catDefTopics', $catDefTopics);
    }

    /**
     * Show the form for creating a new CatDef_Topic.
     *
     * @return Response
     */
    public function create()
    {
        return view('cat_def__topics.create');
    }

    /**
     * Store a newly created CatDef_Topic in storage.
     *
     * @param CreateCatDef_TopicRequest $request
     *
     * @return Response
     */
    public function store(CreateCatDef_TopicRequest $request)
    {
        $input = $request->all();

        $catDefTopic = $this->catDefTopicRepository->create($input);

        Flash::success('Cat Def  Topic saved successfully.');

        return redirect(route('catDefTopics.index'));
    }

    /**
     * Display the specified CatDef_Topic.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $catDefTopic = $this->catDefTopicRepository->find($id);

        if (empty($catDefTopic)) {
            Flash::error('Cat Def  Topic not found');

            return redirect(route('catDefTopics.index'));
        }

        return view('cat_def__topics.show')->with('catDefTopic', $catDefTopic);
    }

    /**
     * Show the form for editing the specified CatDef_Topic.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $catDefTopic = $this->catDefTopicRepository->find($id);

        if (empty($catDefTopic)) {
            Flash::error('Cat Def  Topic not found');

            return redirect(route('catDefTopics.index'));
        }

        return view('cat_def__topics.edit')->with('catDefTopic', $catDefTopic);
    }

    /**
     * Update the specified CatDef_Topic in storage.
     *
     * @param int $id
     * @param UpdateCatDef_TopicRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCatDef_TopicRequest $request)
    {
        $catDefTopic = $this->catDefTopicRepository->find($id);

        if (empty($catDefTopic)) {
            Flash::error('Cat Def  Topic not found');

            return redirect(route('catDefTopics.index'));
        }

        $catDefTopic = $this->catDefTopicRepository->update($request->all(), $id);

        Flash::success('Cat Def  Topic updated successfully.');

        return redirect(route('catDefTopics.index'));
    }

    /**
     * Remove the specified CatDef_Topic from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $catDefTopic = $this->catDefTopicRepository->find($id);

        if (empty($catDefTopic)) {
            Flash::error('Cat Def  Topic not found');

            return redirect(route('catDefTopics.index'));
        }

        $this->catDefTopicRepository->delete($id);

        Flash::success('Cat Def  Topic deleted successfully.');

        return redirect(route('catDefTopics.index'));
    }
}

resources/views/cat_def__topics/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Cat Def  Topic</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'catDefTopics.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('cat_def__topics.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('catDefTopics.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/cat_def__topics/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Cat Def  Topic</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($catDefTopic, ['route' => ['catDefTopics.update', $catDefTopic->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('cat_def__topics.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('catDefTopics.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/cat_def__topics/fields.blade.php
<!-- Brid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('brid', 'Brid:') !!}
    {!! Form::text('brid', null, ['class' => 'form-control']) !!}
</div>

<!-- Optionval Field -->
<div class="form-group col-sm-6">
    {!! Form::label('optionval', 'Optionval:') !!}
    {!! Form::text('optionval', null, ['class' => 'form-control']) !!}
</div>

<!-- Parent Field -->
<div class="form-group col-sm-6">
    {!! Form::label('parent', 'Parent:') !!}
    {!! Form::text('parent', null, ['class' => 'form-control']) !!}
</div>

resources/views/cat_def__topics/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cat Def  Topics</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('catDefTopics.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('cat_def__topics.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/cat_def__topics/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cat Def  Topic Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('catDefTopics.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('cat_def__topics.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/cat_def__topics/show_fields.blade.php
<!-- Brid Field -->
<div class="col-sm-12">
    {!! Form::label('brid', 'Brid:') !!}
    <p>{{ $catDefTopic->brid }}</p>
</div>

<!-- Optionval Field -->
<div class="col-sm-12">
    {!! Form::label('optionval', 'Optionval:') !!}
    <p>{{ $catDefTopic->optionval }}</p>
</div>

<!-- Parent Field -->
<div class="col-sm-12">
    {!! Form::label('parent', 'Parent:') !!}
    <p>{{ $catDefTopic->parent }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $catDefTopic->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $catDefTopic->updated_at }}</p>
</div>

resources/views/cat_def__topics/table.blade.php
<div class="table-responsive">
    <table class="table" id="catDefTopics-table">
        <thead>
            <tr>
                <th>Brid</th>
        <th>Optionval</th>
        <th>Parent</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($catDefTopics as $catDefTopic)
            <tr>
                <td>{{ $catDefTopic->brid }}</td>
            <td>{{ $catDefTopic->optionval }}</td>
            <td>{{ $catDefTopic->parent }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['catDefTopics.destroy', $catDefTopic->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('catDefTopics.show', [$catDefTopic->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('catDefTopics.edit', [$catDefTopic->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>