routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/somepage', function () {
    return view('somepage');
});
Route::get('/pwdresetform', function () {
    return view('pwdresetform');
});

Route::get('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::post('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::get('pwdchange', 'App\Http\Controllers\pwdresetController@pwdreset_steptwo');
Route::get('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');
Route::post('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('pwdresets', App\Http\Controllers\pwdresetController::class);

Route::resource('basicdatas', App\Http\Controllers\basicdatasController::class);

Route::resource('jobs', App\Http\Controllers\jobsController::class);

Route::resource('dtjobs', App\Http\Controllers\dtjobsController::class);

Route::resource('pulldown1s', App\Http\Controllers\pulldown1sController::class);

Route::resource('testfield1s', App\Http\Controllers\testfield1sController::class);

Route::resource('testfield2s', App\Http\Controllers\testfield2sController::class);

Route::resource('testfield3s', App\Http\Controllers\testfield3sController::class);

Route::resource('jobcategories', App\Http\Controllers\jobcategoriesController::class);

Route::resource('articles', App\Http\Controllers\ArticlesController::class);

Route::resource('articlecategories', App\Http\Controllers\ArticlecategoriesController::class);

Route::resource('lessons', App\Http\Controllers\lessonsController::class);

Route::resource('catDefAgeGroups', App\Http\Controllers\CatDef_AgeGroupController::class);

Route::resource('catDefSubjects', App\Http\Controllers\CatDef_SubjectController::class);

Route::resource('catDefTopics', App\Http\Controllers\CatDef_TopicController::class);

Route::resource('catDefConcepts', App\Http\Controllers\CatDef_ConceptController::class);

Route::resource('lessonsTwoCols', App\Http\Controllers\LessonsTwoColsController::class);

Route::resource('lessonsadvs', App\Http\Controllers\LessonsadvController::class);

Route::resource('applicationTrackings', App\Http\Controllers\Application_TrackingController::class);

Route::resource('postAdverts', App\Http\Controllers\Post_AdvertsController::class);

Route::resource('employers', App\Http\Controllers\employerController::class);

Route::resource('employerjobs', App\Http\Controllers\EmployerjobsController::class);

Route::resource('employerJobApplications', App\Http\Controllers\EmployerJobApplicationController::class);

app/Models/EmployerJobApplication.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;



/**
 * Class EmployerJobApplication
 * @package App\Models
 * @version August 5, 2021, 12:43 pm UTC
 *
 * @property string $userid
 * @property string $employerid
 * @property string $jobid
 * @property string $job_bruid
 * @property string $progress
 * @property string $t1
 * @property string $t2
 * @property string $t3
 * @property string $t4
 * @property string $t5
 * @property string $t6
 * @property string $t7
 * @property string $t8
 * @property string $t9
 * @property string $exref0
 * @property string $exref1
 * @property string $exref2
 * @property string $exref3
 * @property string $exref4
 * @property string $exref5
 * @property string $exref6
 * @property string $exref7
 * @property string $exref8
 * @property string $exref9
 */
class EmployerJobApplication extends Model
{


    public $table = 'employer_job_applications';
    



    public $fillable = [
        'userid',
        'employerid',
        'jobid',
        'job_bruid',
        'progress',
        't1',
        't2',
        't3',
        't4',
        't5',
        't6',
        't7',
        't8',
        't9',
        'exref0',
        'exref1',
        'exref2',
        'exref3',
        'exref4',
        'exref5',
        'exref6',
        'exref7',
        'exref8',
        'exref9'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'userid' => 'string',
        'employerid' => 'string',
        'jobid' => 'string',
        'job_bruid' => 'string',
        'progress' => 'string',
        't1' => 'string',
        't2' => 'string',
        't3' => 'string',
        't4' => 'string',
        't5' => 'string',
        't6' => 'string',
        't7' => 'string',
        't8' => 'string',
        't9' => 'string',
        'exref0' => 'string',
        'exref1' => 'string',
        'exref2' => 'string',
        'exref3' => 'string',
        'exref4' => 'string',
        'exref5' => 'string',
        'exref6' => 'string',
        'exref7' => 'string',
        'exref8' => 'string',
        'exref9' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/EmployerJobApplicationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateEmployerjobsRequest;
use App\Http\Requests\UpdateEmployerjobsRequest;
use App\Repositories\EmployerjobsRepository;

use App\Http\Requests\CreateemployerRequest;
use App\Http\Requests\UpdateemployerRequest;
use App\Repositories\employerRepository;


use App\Http\Requests\CreateEmployerJobApplicationRequest;
use App\Http\Requests\UpdateEmployerJobApplicationRequest;
use App\Repositories\EmployerJobApplicationRepository;

use App\Models\User;
use App\Models\Employerjobs;
use App\Models\employer;
use App\Models\EmployerJobApplication;

use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;

use Flash;
use Response;

class EmployerJobApplicationController extends AppBaseController
{
    /** @var  EmployerJobApplicationRepository */
    private $employerJobApplicationRepository;

    public $user = null;

    public function __construct(EmployerJobApplicationRepository $employerJobApplicationRepo)
    {
        $this->employerJobApplicationRepository = $employerJobApplicationRepo;
    }





    public function checkApiUser($request){
        /*
        no-one but a verfied user has any business in this class.
        */
        $token = $request->bearerToken();
        $this->user = User::where('api_token', $token)->first();

        //dd($this->user);
        if($this->user==null){
            exit("Log in, Sucka.");
        }
    }

    public function api_update($id, UpdateEmployerJobApplicationRequest $request){
        $this->checkApiUser($request);
        $jobApplication = $this->employerJobApplicationRepository->find($id);
        if($this->user->id != $jobApplication['userid']){return(Response::json("Not Your Record" , 403)); }
        $jobApplication = $this->employerJobApplicationRepository->update($request->all(), $id);
        return Response::json(true , 200);
    }
    

    public function api_put(Request $request){

        $this->checkApiUser($request);
        $id = $this->user->id;
        $input = $request->all();
        
        //Let's use record ID and BRUID to find the employer-job.        
        if( isset($input['jobid']) and isset($input['job_bruid']) ){
            //scenario 0: The Best: job ID and job BRUID
            //we have a choice, so we'll use ID.
            $employerjobs=employerjobs::query();
            $employerjobs = $employerjobs->find($input['jobid']);
            //if the ID is mistaken, we call fall back to BRUID.
            if(null == $employerjobs){
                $employerjobs=employerjobs::query();
                $employerjobs=$employerjobs->where('bruid', $input['job_bruid']);
                //dd($employerjobs->first());
                $employerjobs = $employerjobs->first();
                if(null == $employerjobs){return Response::json("Record Not Found" , 404);}
            }
            $employerjobs = $employerjobs->toArray();
            //dd($employerjobs);
        }elseif( isset($input['jobid']) and !isset($input['job_bruid']) ){        
            //scenario 1: job ID but no job BRUID
            $employerjobs=employerjobs::query();
            $employerjobs = $employerjobs->find($input['jobid']);
            if(null == $employerjobs){return  Response::json("Record Not Found" , 404);}
            $employerjobs = $employerjobs->toArray();
            //dd($employerjobs);
        }elseif( !isset($input['jobid']) and isset($input['job_bruid']) ){
            //scenario 2: job BRUID but no job ID
            $employerjobs=employerjobs::query();
            $employerjobs=$employerjobs->where('bruid', $input['job_bruid']);
            if(null == $employerjobs->first()){return  Response::json("Record Not Found" , 404);}
            $employerjobs = $employerjobs->first()->toArray();
            //dd($employerjobs);
        }elseif( !isset($input['jobid']) and !isset($input['job_bruid']) ){
            //scenario 3: neither
            return("can't do nuttin fo yo, man");
        }
        //dd($employerjobs);
        
        //let's make sure that this user (candidate) hasn't logged an application already.
        $employerjobscheck=EmployerJobApplication::query();
        $employerjobscheck->where( 'jobid', $employerjobs['id'] );
        $employerjobscheck->where( 'userid', $id );
        $employerjobscheck = $employerjobscheck->first();
        //dd($employerjobscheck);
        if(null != $employerjobscheck){
            return Response::json("Outstanding Application Exists" , 400);
        }

        
        //update userID, employerID, jobID, jobBRUID and progress
        $input['userid'] = $id;
        $input['progress'] =  $employerjobs['pitch'];
        $input['employerid'] =   $employerjobs['employerid'];
        $input['jobid'] =   $employerjobs['id'];
        $input['job_bruid'] =  $employerjobs['bruid'];
        $input['t1'] =  $employerjobs['jobtitle'] . "\n\n" . $employerjobs['jobdescription'];
        //dd($input);
        $jobApplication = $this->employerJobApplicationRepository->create($input);
        return Response::json(true , 200);
    }

    public function api_show(Request $request){
        $this->checkApiUser($request);
        $id = $this->user->id;
        //dd($id);
        $retval = EmployerJobApplication::where('userid', $id)->get();
        return Response::json($retval , 200);
    }

    public function api_delete($id, Request $request){
        $this->checkApiUser($request);
        $this->employerJobApplicationRepository->delete($id);
        return Response::json(true , 200);
    }


    /**
     * Display a listing of the EmployerJobApplication.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $employerJobApplications = $this->employerJobApplicationRepository->all();

        return view('employer_job_applications.index')
            ->with('employerJobApplications', $employerJobApplications);
    }

    /**
     * Show the form for creating a new EmployerJobApplication.
     *
     * @return Response
     */
    public function create()
    {
        return view('employer_job_applications.create');
    }

    /**
     * Store a newly created EmployerJobApplication in storage.
     *
     * @param CreateEmployerJobApplicationRequest $request
     *
     * @return Response
     */
    public function store(CreateEmployerJobApplicationRequest $request)
    {
        $input = $request->all();

        $employerJobApplication = $this->employerJobApplicationRepository->create($input);

        Flash::success('Employer Job Application saved successfully.');

        return redirect(route('employerJobApplications.index'));
    }

    /**
     * Display the specified EmployerJobApplication.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $employerJobApplication = $this->employerJobApplicationRepository->find($id);

        if (empty($employerJobApplication)) {
            Flash::error('Employer Job Application not found');

            return redirect(route('employerJobApplications.index'));
        }

        return view('employer_job_applications.show')->with('employerJobApplication', $employerJobApplication);
    }

    /**
     * Show the form for editing the specified EmployerJobApplication.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $employerJobApplication = $this->employerJobApplicationRepository->find($id);

        if (empty($employerJobApplication)) {
            Flash::error('Employer Job Application not found');

            return redirect(route('employerJobApplications.index'));
        }

        return view('employer_job_applications.edit')->with('employerJobApplication', $employerJobApplication);
    }

    /**
     * Update the specified EmployerJobApplication in storage.
     *
     * @param int $id
     * @param UpdateEmployerJobApplicationRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEmployerJobApplicationRequest $request)
    {
        $employerJobApplication = $this->employerJobApplicationRepository->find($id);

        if (empty($employerJobApplication)) {
            Flash::error('Employer Job Application not found');

            return redirect(route('employerJobApplications.index'));
        }

        $employerJobApplication = $this->employerJobApplicationRepository->update($request->all(), $id);

        Flash::success('Employer Job Application updated successfully.');

        return redirect(route('employerJobApplications.index'));
    }

    /**
     * Remove the specified EmployerJobApplication from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $employerJobApplication = $this->employerJobApplicationRepository->find($id);

        if (empty($employerJobApplication)) {
            Flash::error('Employer Job Application not found');

            return redirect(route('employerJobApplications.index'));
        }

        $this->employerJobApplicationRepository->delete($id);

        Flash::success('Employer Job Application deleted successfully.');

        return redirect(route('employerJobApplications.index'));
    }
}

resources/views/employer_job_applications/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Employer Job Application</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'employerJobApplications.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('employer_job_applications.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('employerJobApplications.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/employer_job_applications/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Employer Job Application</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($employerJobApplication, ['route' => ['employerJobApplications.update', $employerJobApplication->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('employer_job_applications.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('employerJobApplications.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/employer_job_applications/fields.blade.php
<!-- Progress Field -->
<div class="form-group col-sm-6">
    {!! Form::label('progress', 'Progress:') !!}
    {!! Form::text('progress', null, ['class' => 'form-control']) !!}
</div>

<!-- T1 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t1', 'T1:') !!}
    {!! Form::text('t1', null, ['class' => 'form-control']) !!}
</div>

<!-- T2 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t2', 'T2:') !!}
    {!! Form::text('t2', null, ['class' => 'form-control']) !!}
</div>

<!-- T3 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t3', 'T3:') !!}
    {!! Form::text('t3', null, ['class' => 'form-control']) !!}
</div>

<!-- T4 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t4', 'T4:') !!}
    {!! Form::text('t4', null, ['class' => 'form-control']) !!}
</div>

<!-- T5 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t5', 'T5:') !!}
    {!! Form::text('t5', null, ['class' => 'form-control']) !!}
</div>

<!-- T6 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t6', 'T6:') !!}
    {!! Form::text('t6', null, ['class' => 'form-control']) !!}
</div>

<!-- T7 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t7', 'T7:') !!}
    {!! Form::text('t7', null, ['class' => 'form-control']) !!}
</div>

<!-- T8 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t8', 'T8:') !!}
    {!! Form::text('t8', null, ['class' => 'form-control']) !!}
</div>

<!-- T9 Field -->
<div class="form-group col-sm-6">
    {!! Form::label('t9', 'T9:') !!}
    {!! Form::text('t9', null, ['class' => 'form-control']) !!}
</div>

resources/views/employer_job_applications/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Employer Job Applications</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('employerJobApplications.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('employer_job_applications.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/employer_job_applications/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Employer Job Application Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('employerJobApplications.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('employer_job_applications.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/employer_job_applications/show_fields.blade.php
<!-- Userid Field -->
<div class="col-sm-12">
    {!! Form::label('userid', 'Userid:') !!}
    <p>{{ $employerJobApplication->userid }}</p>
</div>

<!-- Employerid Field -->
<div class="col-sm-12">
    {!! Form::label('employerid', 'Employerid:') !!}
    <p>{{ $employerJobApplication->employerid }}</p>
</div>

<!-- Jobid Field -->
<div class="col-sm-12">
    {!! Form::label('jobid', 'Jobid:') !!}
    <p>{{ $employerJobApplication->jobid }}</p>
</div>

<!-- Job Bruid Field -->
<div class="col-sm-12">
    {!! Form::label('job_bruid', 'Job Bruid:') !!}
    <p>{{ $employerJobApplication->job_bruid }}</p>
</div>

<!-- Progress Field -->
<div class="col-sm-12">
    {!! Form::label('progress', 'Progress:') !!}
    <p>{{ $employerJobApplication->progress }}</p>
</div>

<!-- T1 Field -->
<div class="col-sm-12">
    {!! Form::label('t1', 'T1:') !!}
    <p>{{ $employerJobApplication->t1 }}</p>
</div>

<!-- T2 Field -->
<div class="col-sm-12">
    {!! Form::label('t2', 'T2:') !!}
    <p>{{ $employerJobApplication->t2 }}</p>
</div>

<!-- T3 Field -->
<div class="col-sm-12">
    {!! Form::label('t3', 'T3:') !!}
    <p>{{ $employerJobApplication->t3 }}</p>
</div>

<!-- T4 Field -->
<div class="col-sm-12">
    {!! Form::label('t4', 'T4:') !!}
    <p>{{ $employerJobApplication->t4 }}</p>
</div>

<!-- T5 Field -->
<div class="col-sm-12">
    {!! Form::label('t5', 'T5:') !!}
    <p>{{ $employerJobApplication->t5 }}</p>
</div>

<!-- T6 Field -->
<div class="col-sm-12">
    {!! Form::label('t6', 'T6:') !!}
    <p>{{ $employerJobApplication->t6 }}</p>
</div>

<!-- T7 Field -->
<div class="col-sm-12">
    {!! Form::label('t7', 'T7:') !!}
    <p>{{ $employerJobApplication->t7 }}</p>
</div>

<!-- T8 Field -->
<div class="col-sm-12">
    {!! Form::label('t8', 'T8:') !!}
    <p>{{ $employerJobApplication->t8 }}</p>
</div>

<!-- T9 Field -->
<div class="col-sm-12">
    {!! Form::label('t9', 'T9:') !!}
    <p>{{ $employerJobApplication->t9 }}</p>
</div>

<!-- Exref0 Field -->
<div class="col-sm-12">
    {!! Form::label('exref0', 'Exref0:') !!}
    <p>{{ $employerJobApplication->exref0 }}</p>
</div>

<!-- Exref1 Field -->
<div class="col-sm-12">
    {!! Form::label('exref1', 'Exref1:') !!}
    <p>{{ $employerJobApplication->exref1 }}</p>
</div>

<!-- Exref2 Field -->
<div class="col-sm-12">
    {!! Form::label('exref2', 'Exref2:') !!}
    <p>{{ $employerJobApplication->exref2 }}</p>
</div>

<!-- Exref3 Field -->
<div class="col-sm-12">
    {!! Form::label('exref3', 'Exref3:') !!}
    <p>{{ $employerJobApplication->exref3 }}</p>
</div>

<!-- Exref4 Field -->
<div class="col-sm-12">
    {!! Form::label('exref4', 'Exref4:') !!}
    <p>{{ $employerJobApplication->exref4 }}</p>
</div>

<!-- Exref5 Field -->
<div class="col-sm-12">
    {!! Form::label('exref5', 'Exref5:') !!}
    <p>{{ $employerJobApplication->exref5 }}</p>
</div>

<!-- Exref6 Field -->
<div class="col-sm-12">
    {!! Form::label('exref6', 'Exref6:') !!}
    <p>{{ $employerJobApplication->exref6 }}</p>
</div>

<!-- Exref7 Field -->
<div class="col-sm-12">
    {!! Form::label('exref7', 'Exref7:') !!}
    <p>{{ $employerJobApplication->exref7 }}</p>
</div>

<!-- Exref8 Field -->
<div class="col-sm-12">
    {!! Form::label('exref8', 'Exref8:') !!}
    <p>{{ $employerJobApplication->exref8 }}</p>
</div>

<!-- Exref9 Field -->
<div class="col-sm-12">
    {!! Form::label('exref9', 'Exref9:') !!}
    <p>{{ $employerJobApplication->exref9 }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $employerJobApplication->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $employerJobApplication->updated_at }}</p>
</div>

resources/views/employer_job_applications/table.blade.php
<div class="table-responsive">
    <table class="table" id="employerJobApplications-table">
        <thead>
            <tr>
                <th>Progress</th>
        <th>T1</th>
        <th>T2</th>
        <th>T3</th>
        <th>T4</th>
        <th>T5</th>
        <th>T6</th>
        <th>T7</th>
        <th>T8</th>
        <th>T9</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($employerJobApplications as $employerJobApplication)
            <tr>
                <td>{{ $employerJobApplication->progress }}</td>
            <td>{{ $employerJobApplication->t1 }}</td>
            <td>{{ $employerJobApplication->t2 }}</td>
            <td>{{ $employerJobApplication->t3 }}</td>
            <td>{{ $employerJobApplication->t4 }}</td>
            <td>{{ $employerJobApplication->t5 }}</td>
            <td>{{ $employerJobApplication->t6 }}</td>
            <td>{{ $employerJobApplication->t7 }}</td>
            <td>{{ $employerJobApplication->t8 }}</td>
            <td>{{ $employerJobApplication->t9 }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['employerJobApplications.destroy', $employerJobApplication->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('employerJobApplications.show', [$employerJobApplication->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('employerJobApplications.edit', [$employerJobApplication->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>