routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/somepage', function () {
    return view('somepage');
});
Route::get('/pwdresetform', function () {
    return view('pwdresetform');
});

Route::get('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::post('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::get('pwdchange', 'App\Http\Controllers\pwdresetController@pwdreset_steptwo');
Route::get('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');
Route::post('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('pwdresets', App\Http\Controllers\pwdresetController::class);

Route::resource('basicdatas', App\Http\Controllers\basicdatasController::class);

Route::resource('jobs', App\Http\Controllers\jobsController::class);

Route::resource('dtjobs', App\Http\Controllers\dtjobsController::class);

Route::resource('pulldown1s', App\Http\Controllers\pulldown1sController::class);

Route::resource('testfield1s', App\Http\Controllers\testfield1sController::class);

Route::resource('testfield2s', App\Http\Controllers\testfield2sController::class);

Route::resource('testfield3s', App\Http\Controllers\testfield3sController::class);

Route::resource('jobcategories', App\Http\Controllers\jobcategoriesController::class);

Route::resource('articles', App\Http\Controllers\ArticlesController::class);

Route::resource('articlecategories', App\Http\Controllers\ArticlecategoriesController::class);

Route::resource('lessons', App\Http\Controllers\lessonsController::class);

Route::resource('catDefAgeGroups', App\Http\Controllers\CatDef_AgeGroupController::class);

Route::resource('catDefSubjects', App\Http\Controllers\CatDef_SubjectController::class);

Route::resource('catDefTopics', App\Http\Controllers\CatDef_TopicController::class);

Route::resource('catDefConcepts', App\Http\Controllers\CatDef_ConceptController::class);

Route::resource('lessonsTwoCols', App\Http\Controllers\LessonsTwoColsController::class);

Route::resource('lessonsadvs', App\Http\Controllers\LessonsadvController::class);

Route::resource('applicationTrackings', App\Http\Controllers\Application_TrackingController::class);

Route::resource('postAdverts', App\Http\Controllers\Post_AdvertsController::class);

Route::resource('employers', App\Http\Controllers\employerController::class);

Route::resource('employerjobs', App\Http\Controllers\EmployerjobsController::class);

Route::resource('employerJobApplications', App\Http\Controllers\EmployerJobApplicationController::class);

app/Models/CatDef_Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;



/**
 * Class CatDef_Subject
 * @package App\Models
 * @version April 13, 2021, 6:05 pm UTC
 *
 * @property string $brid
 * @property string $optionval
 * @property string $parent
 */
class CatDef_Subject extends Model
{


    public $table = 'cat_def__subjects';
    



    public $fillable = [
        'brid',
        'optionval',
        'parent'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'brid' => 'string',
        'optionval' => 'string',
        'parent' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/CatDef_SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCatDef_SubjectRequest;
use App\Http\Requests\UpdateCatDef_SubjectRequest;
use App\Repositories\CatDef_SubjectRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CatDef_SubjectController extends AppBaseController
{
    /** @var  CatDef_SubjectRepository */
    private $catDefSubjectRepository;

    public function __construct(CatDef_SubjectRepository $catDefSubjectRepo)
    {
        $this->catDefSubjectRepository = $catDefSubjectRepo;
    }

    /**
     * Display a listing of the CatDef_Subject.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $catDefSubjects = $this->catDefSubjectRepository->all();

        return view('cat_def__subjects.index')
            ->with('catDefSubjects', $catDefSubjects);
    }

    /**
     * Show the form for creating a new CatDef_Subject.
     *
     * @return Response
     */
    public function create()
    {
        return view('cat_def__subjects.create');
    }

    /**
     * Store a newly created CatDef_Subject in storage.
     *
     * @param CreateCatDef_SubjectRequest $request
     *
     * @return Response
     */
    public function store(CreateCatDef_SubjectRequest $request)
    {
        $input = $request->all();

        $catDefSubject = $this->catDefSubjectRepository->create($input);

        Flash::success('Cat Def  Subject saved successfully.');

        return redirect(route('catDefSubjects.index'));
    }

    /**
     * Display the specified CatDef_Subject.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $catDefSubject = $this->catDefSubjectRepository->find($id);

        if (empty($catDefSubject)) {
            Flash::error('Cat Def  Subject not found');

            return redirect(route('catDefSubjects.index'));
        }

        return view('cat_def__subjects.show')->with('catDefSubject', $catDefSubject);
    }

    /**
     * Show the form for editing the specified CatDef_Subject.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $catDefSubject = $this->catDefSubjectRepository->find($id);

        if (empty($catDefSubject)) {
            Flash::error('Cat Def  Subject not found');

            return redirect(route('catDefSubjects.index'));
        }

        return view('cat_def__subjects.edit')->with('catDefSubject', $catDefSubject);
    }

    /**
     * Update the specified CatDef_Subject in storage.
     *
     * @param int $id
     * @param UpdateCatDef_SubjectRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCatDef_SubjectRequest $request)
    {
        $catDefSubject = $this->catDefSubjectRepository->find($id);

        if (empty($catDefSubject)) {
            Flash::error('Cat Def  Subject not found');

            return redirect(route('catDefSubjects.index'));
        }

        $catDefSubject = $this->catDefSubjectRepository->update($request->all(), $id);

        Flash::success('Cat Def  Subject updated successfully.');

        return redirect(route('catDefSubjects.index'));
    }

    /**
     * Remove the specified CatDef_Subject from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $catDefSubject = $this->catDefSubjectRepository->find($id);

        if (empty($catDefSubject)) {
            Flash::error('Cat Def  Subject not found');

            return redirect(route('catDefSubjects.index'));
        }

        $this->catDefSubjectRepository->delete($id);

        Flash::success('Cat Def  Subject deleted successfully.');

        return redirect(route('catDefSubjects.index'));
    }
}

resources/views/cat_def__subjects/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Cat Def  Subject</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'catDefSubjects.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('cat_def__subjects.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('catDefSubjects.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/cat_def__subjects/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Cat Def  Subject</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($catDefSubject, ['route' => ['catDefSubjects.update', $catDefSubject->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('cat_def__subjects.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('catDefSubjects.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/cat_def__subjects/fields.blade.php
<!-- Brid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('brid', 'Brid:') !!}
    {!! Form::text('brid', null, ['class' => 'form-control']) !!}
</div>

<!-- Optionval Field -->
<div class="form-group col-sm-6">
    {!! Form::label('optionval', 'Optionval:') !!}
    {!! Form::text('optionval', null, ['class' => 'form-control']) !!}
</div>

<!-- Parent Field -->
<div class="form-group col-sm-6">
    {!! Form::label('parent', 'Parent:') !!}
    {!! Form::text('parent', null, ['class' => 'form-control']) !!}
</div>

resources/views/cat_def__subjects/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cat Def  Subjects</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('catDefSubjects.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('cat_def__subjects.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/cat_def__subjects/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Cat Def  Subject Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('catDefSubjects.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('cat_def__subjects.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/cat_def__subjects/show_fields.blade.php
<!-- Brid Field -->
<div class="col-sm-12">
    {!! Form::label('brid', 'Brid:') !!}
    <p>{{ $catDefSubject->brid }}</p>
</div>

<!-- Optionval Field -->
<div class="col-sm-12">
    {!! Form::label('optionval', 'Optionval:') !!}
    <p>{{ $catDefSubject->optionval }}</p>
</div>

<!-- Parent Field -->
<div class="col-sm-12">
    {!! Form::label('parent', 'Parent:') !!}
    <p>{{ $catDefSubject->parent }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $catDefSubject->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $catDefSubject->updated_at }}</p>
</div>

resources/views/cat_def__subjects/table.blade.php
<div class="table-responsive">
    <table class="table" id="catDefSubjects-table">
        <thead>
            <tr>
                <th>Brid</th>
        <th>Optionval</th>
        <th>Parent</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($catDefSubjects as $catDefSubject)
            <tr>
                <td>{{ $catDefSubject->brid }}</td>
            <td>{{ $catDefSubject->optionval }}</td>
            <td>{{ $catDefSubject->parent }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['catDefSubjects.destroy', $catDefSubject->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('catDefSubjects.show', [$catDefSubject->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('catDefSubjects.edit', [$catDefSubject->id]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>