routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/somepage', function () {
    return view('somepage');
});
Route::get('/pwdresetform', function () {
    return view('pwdresetform');
});

Route::get('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::post('pwdreset', 'App\Http\Controllers\pwdresetController@pwdreset_stepone_web')->name('pwdresetentry');
Route::get('pwdchange', 'App\Http\Controllers\pwdresetController@pwdreset_steptwo');
Route::get('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');
Route::post('pwdresetexe', 'App\Http\Controllers\pwdresetController@pwdreset_stepthree_web');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('pwdresets', App\Http\Controllers\pwdresetController::class);

Route::resource('basicdatas', App\Http\Controllers\basicdatasController::class);

Route::resource('jobs', App\Http\Controllers\jobsController::class);

Route::resource('dtjobs', App\Http\Controllers\dtjobsController::class);

Route::resource('pulldown1s', App\Http\Controllers\pulldown1sController::class);

Route::resource('testfield1s', App\Http\Controllers\testfield1sController::class);

Route::resource('testfield2s', App\Http\Controllers\testfield2sController::class);

Route::resource('testfield3s', App\Http\Controllers\testfield3sController::class);

Route::resource('jobcategories', App\Http\Controllers\jobcategoriesController::class);

Route::resource('articles', App\Http\Controllers\ArticlesController::class);

Route::resource('articlecategories', App\Http\Controllers\ArticlecategoriesController::class);

Route::resource('lessons', App\Http\Controllers\lessonsController::class);

Route::resource('catDefAgeGroups', App\Http\Controllers\CatDef_AgeGroupController::class);

Route::resource('catDefSubjects', App\Http\Controllers\CatDef_SubjectController::class);

Route::resource('catDefTopics', App\Http\Controllers\CatDef_TopicController::class);

Route::resource('catDefConcepts', App\Http\Controllers\CatDef_ConceptController::class);

Route::resource('lessonsTwoCols', App\Http\Controllers\LessonsTwoColsController::class);

Route::resource('lessonsadvs', App\Http\Controllers\LessonsadvController::class);

Route::resource('applicationTrackings', App\Http\Controllers\Application_TrackingController::class);

Route::resource('postAdverts', App\Http\Controllers\Post_AdvertsController::class);

Route::resource('employers', App\Http\Controllers\employerController::class);

Route::resource('employerjobs', App\Http\Controllers\EmployerjobsController::class);

Route::resource('employerJobApplications', App\Http\Controllers\EmployerJobApplicationController::class);

resources/views/dtjobs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Dtjobs</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'dtjobs.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('dtjobs.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('dtjobs.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/dtjobs/datatables_actions.blade.php
{!! Form::open(['route' => ['dtjobs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('dtjobs.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('dtjobs.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/dtjobs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Dtjobs</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($dtjobs, ['route' => ['dtjobs.update', $dtjobs->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('dtjobs.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('dtjobs.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/dtjobs/fields.blade.php
<!-- Bruid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('bruid', 'Bruid:') !!}
    {!! Form::text('bruid', null, ['class' => 'form-control']) !!}
</div>

<!-- Agent Field -->
<div class="form-group col-sm-6">
    {!! Form::label('agent', 'Agent:') !!}
    {!! Form::text('agent', null, ['class' => 'form-control']) !!}
</div>

<!-- Jobreference Field -->
<div class="form-group col-sm-6">
    {!! Form::label('jobreference', 'Jobreference:') !!}
    {!! Form::text('jobreference', null, ['class' => 'form-control']) !!}
</div>

<!-- Jobtitle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('jobtitle', 'Jobtitle:') !!}
    {!! Form::text('jobtitle', null, ['class' => 'form-control']) !!}
</div>

<!-- Jobdescription Field -->
<div class="form-group col-sm-6">
    {!! Form::label('jobdescription', 'Jobdescription:') !!}
    {!! Form::text('jobdescription', null, ['class' => 'form-control']) !!}
</div>

<!-- Salary Field -->
<div class="form-group col-sm-6">
    {!! Form::label('salary', 'Salary:') !!}
    {!! Form::text('salary', null, ['class' => 'form-control']) !!}
</div>

<!-- Jobtype Field -->
<div class="form-group col-sm-6">
    {!! Form::label('jobtype', 'Jobtype:') !!}
    {!! Form::text('jobtype', null, ['class' => 'form-control']) !!}
</div>

<!-- City Field -->
<div class="form-group col-sm-6">
    {!! Form::label('city', 'City:') !!}
    {!! Form::text('city', null, ['class' => 'form-control']) !!}
</div>

<!-- State Field -->
<div class="form-group col-sm-6">
    {!! Form::label('state', 'State:') !!}
    {!! Form::text('state', null, ['class' => 'form-control']) !!}
</div>

<!-- Postcode Field -->
<div class="form-group col-sm-6">
    {!! Form::label('postcode', 'Postcode:') !!}
    {!! Form::text('postcode', null, ['class' => 'form-control']) !!}
</div>

<!-- Country Field -->
<div class="form-group col-sm-6">
    {!! Form::label('country', 'Country:') !!}
    {!! Form::text('country', null, ['class' => 'form-control']) !!}
</div>

<!-- Employer Field -->
<div class="form-group col-sm-6">
    {!! Form::label('employer', 'User:') !!}
    {!! Form::text('employer', null, ['class' => 'form-control']) !!}
</div>

<!-- Employertype Field -->
<div class="form-group col-sm-6">
    {!! Form::label('employertype', 'User Type:') !!}
    {!! Form::text('employertype', null, ['class' => 'form-control']) !!}
</div>

<!-- Category Field -->
<div class="form-group col-sm-6">
    {!! Form::label('category', 'Category:') !!}
    {!! Form::text('category', null, ['class' => 'form-control']) !!}
</div>

<!-- Posteddate Field -->
<div class="form-group col-sm-6">
    {!! Form::label('posteddate', 'Posteddate:') !!}
    {!! Form::text('posteddate', null, ['class' => 'form-control']) !!}
</div>

<!-- Posteddatetext Field -->
<div class="form-group col-sm-6">
    {!! Form::label('posteddatetext', 'Posteddatetext:') !!}
    {!! Form::text('posteddatetext', null, ['class' => 'form-control']) !!}
</div>

resources/views/dtjobs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Dtjobs</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('dtjobs.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('dtjobs.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/dtjobs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Dtjobs Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('dtjobs.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('dtjobs.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/dtjobs/show_fields.blade.php
<!-- Bruid Field -->
<div class="col-sm-12">
    {!! Form::label('bruid', 'Bruid:') !!}
    <p>{{ $dtjobs->bruid }}</p>
</div>

<!-- Agent Field -->
<div class="col-sm-12">
    {!! Form::label('agent', 'Agent:') !!}
    <p>{{ $dtjobs->agent }}</p>
</div>

<!-- Jobreference Field -->
<div class="col-sm-12">
    {!! Form::label('jobreference', 'Jobreference:') !!}
    <p>{{ $dtjobs->jobreference }}</p>
</div>

<!-- Jobtitle Field -->
<div class="col-sm-12">
    {!! Form::label('jobtitle', 'Jobtitle:') !!}
    <p>{{ $dtjobs->jobtitle }}</p>
</div>

<!-- Jobdescription Field -->
<div class="col-sm-12">
    {!! Form::label('jobdescription', 'Jobdescription:') !!}
    <p>{{ $dtjobs->jobdescription }}</p>
</div>

<!-- Salary Field -->
<div class="col-sm-12">
    {!! Form::label('salary', 'Salary:') !!}
    <p>{{ $dtjobs->salary }}</p>
</div>

<!-- Jobtype Field -->
<div class="col-sm-12">
    {!! Form::label('jobtype', 'Jobtype:') !!}
    <p>{{ $dtjobs->jobtype }}</p>
</div>

<!-- City Field -->
<div class="col-sm-12">
    {!! Form::label('city', 'City:') !!}
    <p>{{ $dtjobs->city }}</p>
</div>

<!-- State Field -->
<div class="col-sm-12">
    {!! Form::label('state', 'State:') !!}
    <p>{{ $dtjobs->state }}</p>
</div>

<!-- Postcode Field -->
<div class="col-sm-12">
    {!! Form::label('postcode', 'Postcode:') !!}
    <p>{{ $dtjobs->postcode }}</p>
</div>

<!-- Country Field -->
<div class="col-sm-12">
    {!! Form::label('country', 'Country:') !!}
    <p>{{ $dtjobs->country }}</p>
</div>

<!-- Employer Field -->
<div class="col-sm-12">
    {!! Form::label('employer', 'User:') !!}
    <p>{{ $dtjobs->employer }}</p>
</div>

<!-- Employertype Field -->
<div class="col-sm-12">
    {!! Form::label('employertype', 'User Type:') !!}
    <p>{{ $dtjobs->employertype }}</p>
</div>

<!-- Category Field -->
<div class="col-sm-12">
    {!! Form::label('category', 'Category:') !!}
    <p>{{ $dtjobs->category }}</p>
</div>

<!-- Url Field -->
<div class="col-sm-12">
    {!! Form::label('url', 'Url:') !!}
    <p>{{ $dtjobs->url }}</p>
</div>

<!-- Extref1 Field -->
<div class="col-sm-12">
    {!! Form::label('extref1', 'Extref1:') !!}
    <p>{{ $dtjobs->extref1 }}</p>
</div>

<!-- Extref2 Field -->
<div class="col-sm-12">
    {!! Form::label('extref2', 'Extref2:') !!}
    <p>{{ $dtjobs->extref2 }}</p>
</div>

<!-- Extref3 Field -->
<div class="col-sm-12">
    {!! Form::label('extref3', 'Extref3:') !!}
    <p>{{ $dtjobs->extref3 }}</p>
</div>

<!-- Extref4 Field -->
<div class="col-sm-12">
    {!! Form::label('extref4', 'Extref4:') !!}
    <p>{{ $dtjobs->extref4 }}</p>
</div>

<!-- Extref5 Field -->
<div class="col-sm-12">
    {!! Form::label('extref5', 'Extref5:') !!}
    <p>{{ $dtjobs->extref5 }}</p>
</div>

<!-- Posteddate Field -->
<div class="col-sm-12">
    {!! Form::label('posteddate', 'Posteddate:') !!}
    <p>{{ $dtjobs->posteddate }}</p>
</div>

<!-- Posteddatetext Field -->
<div class="col-sm-12">
    {!! Form::label('posteddatetext', 'Posteddatetext:') !!}
    <p>{{ $dtjobs->posteddatetext }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $dtjobs->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $dtjobs->updated_at }}</p>
</div>

resources/views/dtjobs/table.blade.php
@section('third_party_stylesheets')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush